import { FurniturePreset, SheetConfig } from '../types';

export const STANDARD_SHEET_PRESETS: { name: string; length: number; width: number; desc: string }[] = [
  {
    name: 'Estándar 2440 × 1220 mm (4x8 ft)',
    length: 2440,
    width: 1220,
    desc: 'Medida universal para Triplay, MDF, Aglomerado y Melamina',
  },
  {
    name: 'Melamina Estándar 2440 × 1830 mm (6x8 ft)',
    length: 2440,
    width: 1830,
    desc: 'Formato amplio común en melaminas de carpintería',
  },
  {
    name: 'Tablero Europeo 2500 × 1830 mm',
    length: 2500,
    width: 1830,
    desc: 'Finsa, Egger, Kronospan y marcas europeas',
  },
  {
    name: 'Gran Formato 2750 × 1830 mm',
    length: 2750,
    width: 1830,
    desc: 'Tableros de melamina de altura completa para armarios',
  },
  {
    name: 'Media Lámina 1220 × 1220 mm',
    length: 1220,
    width: 1220,
    desc: 'Cuadrado medio tablero para proyectos pequeños',
  },
  {
    name: 'Cuarto de Lámina 1220 × 600 mm',
    length: 1220,
    width: 600,
    desc: 'Formato retail para bricolaje y proyectos DIY',
  },
  {
    name: 'Imperial 96 × 48 in (4x8 ft)',
    length: 96,
    width: 48,
    desc: 'Medida estándar en pulgadas para Norteamérica',
  },
];

export const PIECE_COLORS = [
  { name: 'Roble Claro', hex: '#d4a373', border: '#b07d4b' },
  { name: 'Nogal Cálido', hex: '#b08968', border: '#7f5539' },
  { name: 'Pino Natural', hex: '#e9c46a', border: '#d4a373' },
  { name: 'Cerezo', hex: '#cb997e', border: '#9c6644' },
  { name: 'Blanco Melamina', hex: '#e2e8f0', border: '#94a3b8' },
  { name: 'Gris Grafito', hex: '#64748b', border: '#334155' },
  { name: 'Azul Taller', hex: '#38bdf8', border: '#0284c7' },
  { name: 'Verde Oliva', hex: '#a3b18a', border: '#588157' },
  { name: 'Terracota', hex: '#e07a5f', border: '#bc4749' },
  { name: 'Haya Nórdica', hex: '#eddcd2', border: '#ddb892' },
];

export const FURNITURE_PRESETS: FurniturePreset[] = [
  {
    id: 'gabinete-cocina-60',
    name: 'Gabinete Bajo de Cocina (60 cm)',
    description: 'Mueble estándar de cocina de 60x60x85 cm con laterales, base, estante y puerta.',
    sheetConfig: {
      length: 2440,
      width: 1830,
      kerf: 3,
      trimMargin: 10,
      unit: 'mm',
    },
    pieces: [
      {
        name: 'Lateral Izquierdo',
        length: 720,
        width: 580,
        quantity: 1,
        allowRotation: true,
        color: '#d4a373',
        edgeBanding: { top: false, bottom: false, left: true, right: false },
      },
      {
        name: 'Lateral Derecho',
        length: 720,
        width: 580,
        quantity: 1,
        allowRotation: true,
        color: '#d4a373',
        edgeBanding: { top: false, bottom: false, left: true, right: false },
      },
      {
        name: 'Piso / Base',
        length: 564,
        width: 580,
        quantity: 1,
        allowRotation: true,
        color: '#b08968',
        edgeBanding: { top: true, bottom: false, left: false, right: false },
      },
      {
        name: 'Estante Regulable',
        length: 562,
        width: 560,
        quantity: 1,
        allowRotation: true,
        color: '#b08968',
        edgeBanding: { top: true, bottom: false, left: false, right: false },
      },
      {
        name: 'Travesaños de Techo',
        length: 564,
        width: 100,
        quantity: 2,
        allowRotation: true,
        color: '#e2e8f0',
        edgeBanding: { top: false, bottom: false, left: false, right: false },
      },
      {
        name: 'Puerta Frontal',
        length: 715,
        width: 595,
        quantity: 1,
        allowRotation: false,
        color: '#e9c46a',
        edgeBanding: { top: true, bottom: true, left: true, right: true },
      },
    ],
  },
  {
    id: 'biblioteca-5-estantes',
    name: 'Estantería / Biblioteca (5 Niveles)',
    description: 'Estantería vertical de 180x80x30 cm con laterales largos y 5 repisas reforzadas.',
    sheetConfig: {
      length: 2440,
      width: 1830,
      kerf: 3.5,
      trimMargin: 10,
      unit: 'mm',
    },
    pieces: [
      {
        name: 'Laterales Principales',
        length: 1800,
        width: 300,
        quantity: 2,
        allowRotation: false,
        color: '#d4a373',
        edgeBanding: { top: false, bottom: false, left: true, right: false },
      },
      {
        name: 'Tapa Superior & Base',
        length: 764,
        width: 300,
        quantity: 2,
        allowRotation: true,
        color: '#b08968',
        edgeBanding: { top: true, bottom: false, left: false, right: false },
      },
      {
        name: 'Estantes Interiores',
        length: 764,
        width: 290,
        quantity: 3,
        allowRotation: true,
        color: '#e9c46a',
        edgeBanding: { top: true, bottom: false, left: false, right: false },
      },
      {
        name: 'Zócalo Frontal',
        length: 764,
        width: 80,
        quantity: 1,
        allowRotation: true,
        color: '#64748b',
        edgeBanding: { top: true, bottom: false, left: false, right: false },
      },
    ],
  },
  {
    id: 'mueble-tv-flotante',
    name: 'Mueble de TV Flotante Minimalista',
    description: 'Mueble suspendido para sala de estar de 140x35x30 cm con 2 divisiones y puertas.',
    sheetConfig: {
      length: 2440,
      width: 1220,
      kerf: 3,
      trimMargin: 10,
      unit: 'mm',
    },
    pieces: [
      {
        name: 'Cubierta Superior',
        length: 1400,
        width: 350,
        quantity: 1,
        allowRotation: false,
        color: '#d4a373',
        edgeBanding: { top: true, bottom: true, left: true, right: true },
      },
      {
        name: 'Base Inferior',
        length: 1400,
        width: 350,
        quantity: 1,
        allowRotation: false,
        color: '#d4a373',
        edgeBanding: { top: true, bottom: false, left: true, right: true },
      },
      {
        name: 'Costados Laterales',
        length: 264,
        width: 350,
        quantity: 2,
        allowRotation: true,
        color: '#b08968',
        edgeBanding: { top: false, bottom: false, left: true, right: false },
      },
      {
        name: 'Divisores Interiores',
        length: 264,
        width: 330,
        quantity: 2,
        allowRotation: true,
        color: '#b08968',
        edgeBanding: { top: false, bottom: false, left: true, right: false },
      },
      {
        name: 'Puertas Abatibles',
        length: 440,
        width: 260,
        quantity: 2,
        allowRotation: false,
        color: '#e2e8f0',
        edgeBanding: { top: true, bottom: true, left: true, right: true },
      },
    ],
  },
  {
    id: 'escritorio-trabajo',
    name: 'Escritorio de Estudio / Oficina',
    description: 'Escritorio ergonómico de 120x60 cm con cajonera lateral y faldón de refuerzo.',
    sheetConfig: {
      length: 2440,
      width: 1830,
      kerf: 3.2,
      trimMargin: 10,
      unit: 'mm',
    },
    pieces: [
      {
        name: 'Tapa de Escritorio Principal',
        length: 1200,
        width: 600,
        quantity: 1,
        allowRotation: false,
        color: '#d4a373',
        edgeBanding: { top: true, bottom: true, left: true, right: true },
      },
      {
        name: 'Patas / Costados',
        length: 730,
        width: 580,
        quantity: 2,
        allowRotation: true,
        color: '#64748b',
        edgeBanding: { top: true, bottom: true, left: true, right: false },
      },
      {
        name: 'Faldón Estructural',
        length: 1164,
        width: 300,
        quantity: 1,
        allowRotation: true,
        color: '#b08968',
        edgeBanding: { top: true, bottom: false, left: false, right: false },
      },
      {
        name: 'Frentes de Cajón',
        length: 380,
        width: 150,
        quantity: 3,
        allowRotation: true,
        color: '#e9c46a',
        edgeBanding: { top: true, bottom: true, left: true, right: true },
      },
      {
        name: 'Laterales de Cajón',
        length: 450,
        width: 120,
        quantity: 6,
        allowRotation: true,
        color: '#e2e8f0',
        edgeBanding: { top: true, bottom: false, left: false, right: false },
      },
    ],
  },
];
